import { Flashcard } from '../types';

export const FLASHCARD_BANK: Flashcard[] = [
  // Plants & Nature (Grade 1-3)
  {
    id: 'fc_plant_san',
    hindi_word: 'पौधा / पेड़ (Plant / Tree)',
    vernacular_word: 'ᱫᱟᱨᱮ (दारे)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Dare',
    icon_name: 'Sprout',
    category: 'plants',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'पेड़ हमें ताज़ी हवा और फल देते हैं।',
    example_sentence_vernacular: 'ᱫᱟᱨᱮ ᱫᱚ ᱟᱵᱚ ᱥᱟᱯᱷᱟ ᱦᱚᱭ ᱟᱨ ᱡᱚ ᱮ ᱮᱢᱟ ᱵᱚᱱᱟ।'
  },
  {
    id: 'fc_plant_mun',
    hindi_word: 'पेड़ / पौधा (Tree / Plant)',
    vernacular_word: 'दारू / दारु (Daaru)',
    vernacular_script: 'Devanagari',
    romanized: 'Daaru',
    icon_name: 'Sprout',
    category: 'plants',
    grade: 1,
    target_language: 'mundari',
    example_sentence_hindi: 'पेड़ हमें फल देते हैं।',
    example_sentence_vernacular: 'दारू आबु के जोः एमाबुआ।'
  },
  {
    id: 'fc_root_san',
    hindi_word: 'जड़ (Root)',
    vernacular_word: 'ᱨᱮᱦᱮᱫ (रेहेद)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Rehed',
    icon_name: 'Anchor',
    category: 'plants',
    grade: 2,
    target_language: 'santhali',
    example_sentence_hindi: 'जड़ें पौधे को मिट्टी में थामे रखती हैं।',
    example_sentence_vernacular: 'ᱨᱮᱦᱮᱫ ᱫᱚ ᱫᱟᱨᱮ ᱦᱟᱥᱟ ᱨᱮ ᱠᱮᱴᱮᱡ ᱛᱮ ᱥᱟᱵ ᱫᱚᱦᱚᱭᱟ।'
  },
  {
    id: 'fc_root_mun',
    hindi_word: 'जड़ (Root)',
    vernacular_word: 'दातु / रेहेद (Datu)',
    vernacular_script: 'Devanagari',
    romanized: 'Daatu',
    icon_name: 'Anchor',
    category: 'plants',
    grade: 2,
    target_language: 'mundari',
    example_sentence_hindi: 'जड़ें मिट्टी में होती हैं।',
    example_sentence_vernacular: 'दातु हासा रे ताएना।'
  },
  {
    id: 'fc_leaf_san',
    hindi_word: 'पत्ता / पत्ती (Leaf)',
    vernacular_word: 'ᱥᱟᱠᱟᱢ (साकाम)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Sakam',
    icon_name: 'Leaf',
    category: 'plants',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'पत्तियां हरी होती हैं।',
    example_sentence_vernacular: 'ᱥᱟᱠᱟᱢ ᱫᱚ ᱦᱟᱹᱨᱭᱟᱹᱲ ᱜᱮᱭᱟ।'
  },
  {
    id: 'fc_leaf_mun',
    hindi_word: 'पत्ता (Leaf)',
    vernacular_word: 'साकम (Sakam)',
    vernacular_script: 'Devanagari',
    romanized: 'Sakam',
    icon_name: 'Leaf',
    category: 'plants',
    grade: 1,
    target_language: 'mundari',
    example_sentence_hindi: 'पत्ते हरे होते हैं।',
    example_sentence_vernacular: 'साकम हरियर ताएना।'
  },
  {
    id: 'fc_flower_san',
    hindi_word: 'फूल (Flower)',
    vernacular_word: 'ᱵᱟᱦᱟ (बाहा)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Baha',
    icon_name: 'Flower2',
    category: 'plants',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'बगीचे में सुंदर फूल खिले हैं।',
    example_sentence_vernacular: 'ᱵᱟᱜᱟᱱ ᱨᱮ ᱪᱚᱨᱚᱠ ᱵᱟᱦᱟ ᱯᱷᱩᱴᱟᱹᱣ ᱟᱠᱟᱱᱟ।'
  },
  {
    id: 'fc_flower_mun',
    hindi_word: 'फूल (Flower)',
    vernacular_word: 'बा / बाहा (Baha)',
    vernacular_script: 'Devanagari',
    romanized: 'Baha',
    icon_name: 'Flower2',
    category: 'plants',
    grade: 1,
    target_language: 'mundari',
    example_sentence_hindi: 'फूल सुंदर होते हैं।',
    example_sentence_vernacular: 'बाहा सुकुर ताएना।'
  },
  {
    id: 'fc_fruit_san',
    hindi_word: 'फल (Fruit)',
    vernacular_word: 'ᱡᱚ (जो)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Jo',
    icon_name: 'Apple',
    category: 'plants',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'मीठा फल खाओ।',
    example_sentence_vernacular: 'ᱦᱮᱲᱮᱢ ᱡᱚ ᱡᱚᱢ ᱢᱮ।'
  },

  // Water Sources (Grade 2-4)
  {
    id: 'fc_water_san',
    hindi_word: 'पानी / जल (Water)',
    vernacular_word: 'ᱫᱟᱜ (दाग)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Daag',
    icon_name: 'Droplets',
    category: 'water',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'साफ़ पानी पियो।',
    example_sentence_vernacular: 'ᱥᱟᱯᱷᱟ ᱫᱟᱜ ᱧᱩᱭ ᱢᱮ।'
  },
  {
    id: 'fc_water_mun',
    hindi_word: 'पानी / जल (Water)',
    vernacular_word: 'दाः (Daah)',
    vernacular_script: 'Devanagari',
    romanized: 'Daah',
    icon_name: 'Droplets',
    category: 'water',
    grade: 1,
    target_language: 'mundari',
    example_sentence_hindi: 'साफ़ पानी पियो।',
    example_sentence_vernacular: 'सोफ़ा दाः नुः मे।'
  },
  {
    id: 'fc_river_san',
    hindi_word: 'नदी (River)',
    vernacular_word: 'ᱜᱟᱰᱟ (गाडा)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Gada',
    icon_name: 'Waves',
    category: 'water',
    grade: 2,
    target_language: 'santhali',
    example_sentence_hindi: 'नदी का पानी बहता है।',
    example_sentence_vernacular: 'ᱜᱟᱰᱟ ᱫᱟᱜ ᱞᱤᱸᱡᱤᱱ ᱠᱟᱱᱟ।'
  },
  {
    id: 'fc_river_mun',
    hindi_word: 'नदी (River)',
    vernacular_word: 'गड़ा (Gada)',
    vernacular_script: 'Devanagari',
    romanized: 'Gada',
    icon_name: 'Waves',
    category: 'water',
    grade: 2,
    target_language: 'mundari',
    example_sentence_hindi: 'नदी में साफ़ पानी है।',
    example_sentence_vernacular: 'गड़ा रे सोफ़ा दाः मेनाः।'
  },
  {
    id: 'fc_rain_san',
    hindi_word: 'वर्षा / बारिश (Rain)',
    vernacular_word: 'ᱫᱟᱜ ᱡᱟᱹᱲᱤ (दाग जाड़ी)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Daag Jari',
    icon_name: 'CloudRain',
    category: 'water',
    grade: 2,
    target_language: 'santhali',
    example_sentence_hindi: 'बारिश हो रही है।',
    example_sentence_vernacular: 'ᱫᱟᱜ ᱡᱟᱹᱲᱤ ᱦᱩᱭᱩᱜ ᱠᱟᱱᱟ।'
  },
  {
    id: 'fc_sun_san',
    hindi_word: 'सूरज / सूर्य (Sun)',
    vernacular_word: 'ᱥᱤᱧ ᱵᱮᱲᱟ (सिञ बेड़ा)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Sinj Bera',
    icon_name: 'Sun',
    category: 'nature',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'सूरज पूरब से निकलता है।',
    example_sentence_vernacular: 'ᱥᱤᱧ ᱵᱮᱲᱟ ᱯᱩᱨᱩᱵᱽ ᱠᱷᱚᱱ ᱨᱟᱠᱟᱵᱼᱟ।'
  },

  // Body Parts (Grade 1-2)
  {
    id: 'fc_eye_san',
    hindi_word: 'आँख (Eye)',
    vernacular_word: 'ᱢᱮᱫ (मेद)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Med',
    icon_name: 'Eye',
    category: 'body',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'आँखों से हम देखते हैं।',
    example_sentence_vernacular: 'ᱢᱮᱫ ᱛᱮ ᱟᱵᱚ ᱵᱚᱱ ᱧᱮᱞᱟ।'
  },
  {
    id: 'fc_ear_san',
    hindi_word: 'कान (Ear)',
    vernacular_word: 'ᱞᱩᱛᱩᱨ (लुतुर)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Lutur',
    icon_name: 'Ear',
    category: 'body',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'कानों से हम सुनते हैं।',
    example_sentence_vernacular: 'ᱞᱩᱛᱩᱨ ᱛᱮ ᱟᱵᱚ ᱵᱚᱱ ᱟᱧᱡᱚᱢᱟ।'
  },
  {
    id: 'fc_hand_san',
    hindi_word: 'हाथ (Hand)',
    vernacular_word: 'ᱛᱤ (ती)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Ti',
    icon_name: 'Hand',
    category: 'body',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'हाथों से हम लिखते हैं।',
    example_sentence_vernacular: 'ᱛᱤ ᱛᱮ ᱟᱵᱚ ᱵᱚᱱ ᱚᱞᱟ।'
  },

  // Math Numbers (Grade 1-3)
  {
    id: 'fc_num_1_san',
    hindi_word: 'एक (1 / One)',
    vernacular_word: 'ᱢᱤᱫ (मिद)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Mid',
    icon_name: 'Binary',
    category: 'math',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'एक पेड़',
    example_sentence_vernacular: 'ᱢᱤᱫᱴᱟᱝ ᱫᱟᱨᱮ'
  },
  {
    id: 'fc_num_2_san',
    hindi_word: 'दो (2 / Two)',
    vernacular_word: 'ᱵᱟᱨ (बार)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Bar',
    icon_name: 'Binary',
    category: 'math',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'दो फूल',
    example_sentence_vernacular: 'ᱵᱟᱨᱭᱟ ᱵᱟᱦᱟ'
  },
  {
    id: 'fc_num_3_san',
    hindi_word: 'तीन (3 / Three)',
    vernacular_word: 'ᱯᱮ (पे)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Pe',
    icon_name: 'Binary',
    category: 'math',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'तीन पत्तियां',
    example_sentence_vernacular: 'ᱯᱮᱭᱟ ᱥᱟᱠᱟᱢ'
  },
  {
    id: 'fc_add_san',
    hindi_word: 'जोड़ना / मिलाना (Addition)',
    vernacular_word: 'ᱢᱮᱥᱟ (मेसा)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Mesa',
    icon_name: 'PlusCircle',
    category: 'math',
    grade: 2,
    target_language: 'santhali',
    example_sentence_hindi: 'दो और तीन को मिलाओ।',
    example_sentence_vernacular: 'ᱵᱟᱨ ᱟᱨ ᱯᱮ ᱢᱮᱥᱟᱭ ᱢᱮ।'
  },

  // School Commands (Grade 1-5)
  {
    id: 'fc_read_san',
    hindi_word: 'पढ़ना / किताब पढ़ो (Read)',
    vernacular_word: 'ᱯᱟᱲᱦᱟᱣ (पढ़ाव)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Parhaw',
    icon_name: 'BookOpen',
    category: 'school',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'किताब पढ़ो।',
    example_sentence_vernacular: 'ᱯᱩᱛᱷᱤ ᱯᱟᱲᱦᱟᱣ ᱢᱮ।'
  },
  {
    id: 'fc_write_san',
    hindi_word: 'लिखना / लिखो (Write)',
    vernacular_word: 'ᱚᱞ (ओल)',
    vernacular_script: 'Ol Chiki & Devanagari',
    romanized: 'Ol',
    icon_name: 'PenTool',
    category: 'school',
    grade: 1,
    target_language: 'santhali',
    example_sentence_hindi: 'कॉपी में लिखो।',
    example_sentence_vernacular: 'ᱠᱷᱟᱛᱟ ᱨᱮ ᱚᱞ ᱢᱮ।'
  }
];
